[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "https://tree-removal-leadgen.netlify.app/*"
  to = "https://tree-removal-leadgen.netlify.app/:splat"
  status = 301!
  force = true
